version: '3.8'

services:
  app:
    container_name: z3
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8090:8090"
    env_file:
      - .env.dev
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./:/app:cached
    networks:
      - zsync-network

  valkeree:
    image: valkey/valkey:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - valkey_data:/data
    command: valkey-server --appendonly yes
    healthcheck:
      test: ["CMD", "valkey-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - zsync-network

  # redis insight works with Valkey
  redis-insight:
    image: redis/redisinsight:latest
    ports:
      - "5540:5540"
    volumes:
      - redisinsight_data:/data
    depends_on:
      - valkeree
    networks:
      - zsync-network

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=dev-root
      - POSTGRES_DB=zedsync
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d
      #- ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d zedsync"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - zsync-network

volumes:
  postgres_data:
  valkey_data:
  redisinsight_data:
  air_tmp:

networks:
  zsync-network:
    driver: bridge
